import {
  Trade,
  LibraryResource,
  Question,
  ITIInstitute,
  RoleInfo,
  DirectorateDistrictSummary,
  StateCircular,
  AssessmentBlueprint,
  ITIBatch,
  ITILabSession,
  TraineeAccount,
  TraineeMistakeItem,
} from './types';

export const UP_ITI_INSTITUTES: ITIInstitute[] = [
  { code: 'ITI-0101', name: 'Govt. ITI Aliganj', district: 'Lucknow', type: 'Government' },
  { code: 'ITI-0102', name: 'Govt. ITI Pandu Nagar', district: 'Kanpur Nagar', type: 'Government' },
  { code: 'ITI-0103', name: 'Govt. ITI Naini', district: 'Prayagraj', type: 'Government' },
  { code: 'ITI-0104', name: 'Govt. ITI Karaundi', district: 'Varanasi', type: 'Government' },
  { code: 'ITI-0105', name: 'Govt. ITI Meerut Cantt', district: 'Meerut', type: 'Government' },
  { code: 'ITI-0106', name: 'Govt. ITI Agra', district: 'Agra', type: 'Government' },
  { code: 'ITI-0107', name: 'Govt. ITI Chharra', district: 'Aligarh', type: 'Government' },
  { code: 'ITI-0108', name: 'Govt. ITI Gorakhpur', district: 'Gorakhpur', type: 'Government' },
  { code: 'ITI-0109', name: 'Govt. ITI Jhansi', district: 'Jhansi', type: 'Government' },
  { code: 'ITI-0110', name: 'Govt. ITI Bareilly', district: 'Bareilly', type: 'Government' },
  { code: 'ITI-0111', name: 'Govt. ITI Ayodhya (Faizabad)', district: 'Ayodhya', type: 'Government' },
  { code: 'ITI-0112', name: 'Govt. ITI Moradabad', district: 'Moradabad', type: 'Government' },
  { code: 'ITI-0113', name: 'Govt. ITI Saharanpur', district: 'Saharanpur', type: 'Government' },
  { code: 'ITI-0114', name: 'Govt. ITI Banda', district: 'Banda', type: 'Government' },
  { code: 'ITI-0115', name: 'Govt. ITI Azamgarh', district: 'Azamgarh', type: 'Government' },
];

export const TRADES: Trade[] = [
  {
    id: 'electrician',
    code: '0231',
    name: {
      en: 'Electrician',
      hi: 'इलेक्ट्रीशियन',
    },
    category: 'engineering',
    duration: '2 Years (4 Semesters)',
    semesterCount: 4,
    icon: 'Zap',
    description: {
      en: 'Electrical machines, wiring, transformers, AC/DC motors, safety standards & power distribution systems.',
      hi: 'विद्युत मशीनें, वायरिंग, ट्रांसफार्मर, एसी/डीसी मोटर, सुरक्षा मानक और विद्युत वितरण प्रणालियां।',
    },
    totalBooks: 18,
    totalQuestions: 650,
  },
  {
    id: 'fitter',
    code: '0227',
    name: {
      en: 'Fitter',
      hi: 'फ़िटर',
    },
    category: 'engineering',
    duration: '2 Years (4 Semesters)',
    semesterCount: 4,
    icon: 'Wrench',
    description: {
      en: 'Bench work, precision measuring instruments, lathe operation, drilling, limits & fits, mechanical assembly.',
      hi: 'बेंच वर्क, सटीक मापक यंत्र, लेथ संचालन, ड्रिलिंग, लिमिट्स एवं फिट्स तथा यांत्रिक असेंबली।',
    },
    totalBooks: 16,
    totalQuestions: 580,
  },
  {
    id: 'copa',
    code: '0242',
    name: {
      en: 'COPA (Computer Operator & Programming Assistant)',
      hi: 'कोपा (कंप्यूटर ऑपरेटर एवं प्रोग्रामिंग असिस्टेंट)',
    },
    category: 'non-engineering',
    duration: '1 Year (2 Semesters)',
    semesterCount: 2,
    icon: 'Monitor',
    description: {
      en: 'Computer hardware, OS, MS Office, Database (MySQL/Access), Python/JavaScript basics, cyber security & accounting software.',
      hi: 'कंप्यूटर हार्डवेयर, ओएस, एमएस ऑफिस, डेटाबेस, प्रोग्रामिंग बेसिक्स, साइबर सुरक्षा एवं एकाउंटिंग सॉफ्टवेयर।',
    },
    totalBooks: 14,
    totalQuestions: 520,
  },
  {
    id: 'welder',
    code: '0246',
    name: {
      en: 'Welder',
      hi: 'वेल्डर',
    },
    category: 'engineering',
    duration: '1 Year (2 Semesters)',
    semesterCount: 2,
    icon: 'Flame',
    description: {
      en: 'Shielded Metal Arc (SMAW), TIG, MIG/MAG, Oxy-Acetylene gas cutting, weld metallurgy and non-destructive testing.',
      hi: 'एसएमएडब्ल्यू, टिग (TIG), मिग (MIG) वेल्डिंग, गैस कटिंग, वेल्ड धातु विज्ञान एवं परीक्षण।',
    },
    totalBooks: 12,
    totalQuestions: 440,
  },
  {
    id: 'electronic-mechanic',
    code: '0219',
    name: {
      en: 'Electronic Mechanic',
      hi: 'इलेक्ट्रॉनिक मैकेनिक',
    },
    category: 'engineering',
    duration: '2 Years (4 Semesters)',
    semesterCount: 4,
    icon: 'Cpu',
    description: {
      en: 'Semiconductors, SMD soldering, microcontrollers, digital circuits, PCB troubleshooting & instrumentation.',
      hi: 'अर्धचालक, एसएमडी सोल्डरिंग, माइक्रोकंट्रोलर, डिजिटल सर्किट, पीसीबी समस्या निवारण।',
    },
    totalBooks: 15,
    totalQuestions: 490,
  },
  {
    id: 'mechanic-diesel',
    code: '0226',
    name: {
      en: 'Mechanic Diesel',
      hi: 'मैकेनिक डीजल',
    },
    category: 'engineering',
    duration: '1 Year (2 Semesters)',
    semesterCount: 2,
    icon: 'Truck',
    description: {
      en: 'Diesel engine overhauling, fuel injection systems, turbochargers, emissions & diagnostic scanner systems.',
      hi: 'डीजल इंजन ओवरहालिंग, फ्यूल इंजेक्शन सिस्टम, टर्बोचार्जर एवं उत्सर्जन नियंत्रण प्रणालियां।',
    },
    totalBooks: 11,
    totalQuestions: 390,
  },
  {
    id: 'employability-skills',
    code: '0001',
    name: {
      en: 'Employability Skills (Common for All Trades)',
      hi: 'एम्प्लॉयबिलिटी स्किल्स (सभी ट्रेड्स हेतु)',
    },
    category: 'workshop-common',
    duration: '120 Hours (Integrated)',
    semesterCount: 2,
    icon: 'Briefcase',
    description: {
      en: 'English literacy, communication skills, IT literacy, entrepreneurship, occupational safety, POSH & green skills.',
      hi: 'अंग्रेजी साक्षरता, संचार कौशल, कंप्यूटर ज्ञान, उद्यमिता, व्यावसायिक सुरक्षा एवं हरित कौशल।',
    },
    totalBooks: 8,
    totalQuestions: 450,
  },
  {
    id: 'workshop-calc-science',
    code: '0002',
    name: {
      en: 'Workshop Calculation & Science (WCS)',
      hi: 'कार्यशाला गणना एवं विज्ञान (WCS)',
    },
    category: 'workshop-common',
    duration: 'Integrated CTS Course',
    semesterCount: 2,
    icon: 'Calculator',
    description: {
      en: 'Applied units, algebra, trigonometry, heat & temperature, speed & velocity, work, power and electrical energy.',
      hi: 'इकाइयां, बीजगणित, त्रिकोणमिति, ऊष्मा और तापमान, गति और वेग, कार्य, शक्ति एवं विद्युत ऊर्जा।',
    },
    totalBooks: 10,
    totalQuestions: 480,
  },
];

export const LIBRARY_RESOURCES: LibraryResource[] = [
  {
    id: 'res-elec-01',
    tradeId: 'electrician',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'Electrician 1st Year Trade Theory - NIMI Standard (Vol 1 & 2)',
      hi: 'इलेक्ट्रीशियन प्रथम वर्ष ट्रेड थ्योरी - निमी मानक (भाग 1 एवं 2)',
    },
    authorOrSource: 'NIMI / DGT Bharat Skills',
    type: 'pdf',
    fileSize: '14.8 MB',
    downloadUrl: '#download-pdf-elec-1',
    isNimiStandard: true,
    tags: ['NIMI Textbook', 'Ohm Law', 'DC Circuits', 'Magnetism', 'Safety'],
    readTime: '42 Modules',
    summary: {
      en: 'Complete 1st year syllabus covering basic electricity, conductors, insulators, soldering techniques, resistor color codes, and series-parallel circuit laws.',
      hi: 'मूलभूत विद्युत, चालक, अचालक, सोल्डरिंग तकनीक, प्रतिरोधक कलर कोडिंग एवं सीरीज-समानांतर परिपथ नियमों का सम्पूर्ण विवरण।',
    },
  },
  {
    id: 'res-elec-02',
    tradeId: 'electrician',
    yearOrSem: 2,
    subject: 'Trade Theory',
    title: {
      en: 'Electrician 2nd Year: 3-Phase Induction Motors & Alternators',
      hi: 'इलेक्ट्रीशियन द्वितीय वर्ष: 3-फेज इंडक्शन मोटर एवं अल्टरनेटर',
    },
    authorOrSource: 'Directorate of Training & Employment UP / NIMI',
    type: 'pdf',
    fileSize: '19.2 MB',
    downloadUrl: '#download-pdf-elec-2',
    isNimiStandard: true,
    tags: ['AC Motors', 'Alternator', 'DOL Starter', 'Transformer', 'Substation'],
    readTime: '38 Modules',
    summary: {
      en: 'In-depth coverage of synchronous generators, squirrel-cage induction motors, slip ring motors, transformer oil testing, and HT/LT distribution panels.',
      hi: 'तुल्यकालिक जनरेटर, स्क्विरल-केज इंडक्शन मोटर, स्लिप रिंग मोटर, ट्रांसफार्मर ऑयल टेस्टिंग और एचटी/एलटी पैनल का विस्तृत अध्ययन।',
    },
  },
  {
    id: 'res-elec-03',
    tradeId: 'electrician',
    yearOrSem: 1,
    subject: 'Trade Practical',
    title: {
      en: 'Workshop Practical Handbook: Domestic Wiring & Earthing Procedures',
      hi: 'कार्यशाला प्रायोगिक पुस्तिका: घरेलू वायरिंग एवं अर्थिंग प्रक्रिया',
    },
    authorOrSource: 'State Council for Vocational Training (SCVT) UP',
    type: 'practical',
    fileSize: '8.4 MB',
    downloadUrl: '#download-practical-elec-1',
    isNimiStandard: true,
    tags: ['Pipe Earthing', 'Plate Earthing', 'Staircase Wiring', 'Megger Testing'],
    readTime: '24 Job Sheets',
    summary: {
      en: 'Step-by-step job sheets for wiring installation, staircase switch setup, pipe/plate earthing installation as per IS:3043 and insulation resistance testing using Megger.',
      hi: 'घरेलू वायरिंग, सीढ़ी वायरिंग, पाइप एवं प्लेट अर्थिंग और मेगर द्वारा इंसुलेशन प्रतिरोध परीक्षण की चरणबद्ध जॉब शीट।',
    },
  },
  {
    id: 'res-elec-04',
    tradeId: 'electrician',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'Video Masterclass: Working Principle of DC Generators & Commutation (Hindi)',
      hi: 'वीडियो मास्टरक्लास: डीसी जनरेटर का कार्य सिद्धांत और कम्यूटेशन (हिंदी)',
    },
    authorOrSource: 'UP ITI Digital Media Cell, Lucknow',
    type: 'video',
    duration: '45 mins',
    downloadUrl: '#watch-video-elec-1',
    isNimiStandard: true,
    tags: ['Video Lecture', 'Fleming Right Hand Rule', 'Armature Reaction'],
    summary: {
      en: 'High-definition bilingual visual demonstration of Fleming\'s Right Hand rule, DC generator construction, interpoles, and reducing armature sparking.',
      hi: 'फ्लेमिंग के दाएं हाथ के नियम, डीसी जनरेटर संरचना और कम्यूटेशन स्पार्किंग दूर करने की सचित्र हिंदी व्याख्या।',
    },
  },
  {
    id: 'res-fit-01',
    tradeId: 'fitter',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'Fitter Trade Theory 1st Year: Precision Measuring & Bench Work - NIMI',
      hi: 'फ़िटर ट्रेड थ्योरी प्रथम वर्ष: सूक्ष्म मापी यंत्र एवं बेंच वर्क - निमी',
    },
    authorOrSource: 'NIMI Bharat Skills',
    type: 'pdf',
    fileSize: '16.1 MB',
    downloadUrl: '#download-pdf-fit-1',
    isNimiStandard: true,
    tags: ['Vernier Caliper', 'Micrometer', 'Bevel Protractor', 'Filing', 'Hacksawing'],
    readTime: '36 Modules',
    summary: {
      en: 'Theory and zero-error calibration of Vernier calipers, micrometers, dial test indicators, hacksaw blades, files, and heat treatment of carbon steels.',
      hi: 'वर्नियर कैलिपर, माइक्रोमीटर, डायल टेस्ट इंडिकेटर, हेक्सा, फाइलें और कार्बन स्टील के ऊष्मा उपचार का मानक अध्ययन।',
    },
  },
  {
    id: 'res-fit-02',
    tradeId: 'fitter',
    yearOrSem: 2,
    subject: 'Trade Practical',
    title: {
      en: 'Fitter 2nd Year: Lathe Machine Operation, Taper Turning & Thread Cutting Job Manual',
      hi: 'फ़िटर द्वितीय वर्ष: लेथ मशीन संचालन, टेपर टर्निंग एवं थ्रेड कटिंग जॉब मैनुअल',
    },
    authorOrSource: 'SCVT Uttar Pradesh Technical Board',
    type: 'practical',
    fileSize: '11.5 MB',
    downloadUrl: '#download-fit-lathe-job',
    isNimiStandard: true,
    tags: ['Lathe Chuck', 'Taper Turning', 'V-Thread Cutting', 'Tolerances'],
    readTime: '30 Job Sheets',
    summary: {
      en: 'Practical steps for 3-jaw & 4-jaw chuck centering, compound rest taper calculation, V-thread pitches, and knurling operations with dimensional tolerances.',
      hi: '3-जॉ एवं 4-जॉ चक सेंटरिंग, कंपाउंड रेस्ट टेपर गणना, वी-थ्रेड पिच कटिंग और नर्लिंग ऑपरेशन की गाइड।',
    },
  },
  {
    id: 'res-copa-01',
    tradeId: 'copa',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'COPA CTS Coursebook: Computer Fundamentals, Operating Systems & Database Management',
      hi: 'कोपा पाठ्यक्रम: कंप्यूटर फंडामेंटल, ऑपरेटिंग सिस्टम एवं डेटाबेस मैनेजमेंट',
    },
    authorOrSource: 'NIMI / DGT New Delhi',
    type: 'pdf',
    fileSize: '12.4 MB',
    downloadUrl: '#download-copa-pdf-1',
    isNimiStandard: true,
    tags: ['Windows 11', 'Linux CLI', 'SQL', 'DBMS', 'Computer Networking'],
    readTime: '28 Modules',
    summary: {
      en: 'Covers BIOS settings, Linux bash terminal commands, relational database design with MySQL, table constraints, SQL queries, and local area network topologies.',
      hi: 'बायोस सेटिंग्स, लिनक्स टर्मिनल कमांड, मायएसक्यूएल रिलेशनल डेटाबेस, टेबल कंस्ट्रेंट्स एवं नेटवर्किंग टोपोलॉजी।',
    },
  },
  {
    id: 'res-copa-02',
    tradeId: 'copa',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'COPA Practical Lab Guide: Web Design (HTML, CSS, JavaScript) & Cyber Law',
      hi: 'कोपा प्रैक्टिकल लैब गाइड: वेब डिजाइन (एचटीएमएल, सीएसएस, जावास्क्रिप्ट) एवं साइबर कानून',
    },
    authorOrSource: 'UP ITI Curriculum Development Cell',
    type: 'practical',
    fileSize: '9.8 MB',
    downloadUrl: '#download-copa-web-lab',
    isNimiStandard: true,
    tags: ['HTML5', 'CSS Flexbox', 'JavaScript DOM', 'IT Act 2000'],
    readTime: '22 Lab Exercises',
    summary: {
      en: 'Hands-on lab programs for creating responsive forms, CSS layout styling, client-side validation using JS, and essential provisions of the Information Technology Act 2000.',
      hi: 'रेस्पॉन्सिव फॉर्म, सीएसएस फ्लेक्सबॉक्स, जावास्क्रिप्ट वैलिडेशन और आईटी एक्ट 2000 के मुख्य प्रावधानों के प्रैक्टिकल।',
    },
  },
  {
    id: 'res-weld-01',
    tradeId: 'welder',
    yearOrSem: 1,
    subject: 'Trade Theory',
    title: {
      en: 'Welder Trade Theory & NDT Inspection Handbook - NIMI',
      hi: 'वेल्डर ट्रेड थ्योरी एवं एनडीटी परीक्षण पुस्तिका - निमी',
    },
    authorOrSource: 'NIMI / Bharat Skills',
    type: 'pdf',
    fileSize: '13.2 MB',
    downloadUrl: '#download-weld-pdf',
    isNimiStandard: true,
    tags: ['SMAW', 'TIG Welding', 'MIG Welding', 'Gas Cutting', 'Dye Penetrant'],
    readTime: '32 Modules',
    summary: {
      en: 'Oxy-acetylene torch adjustment, arc blow causes & remedies, shielding gases (Argon/CO2), welding defects, and Dye Penetrant non-destructive testing.',
      hi: 'गैस वेल्डिंग टॉर्च संतुलन, आर्क ब्लो के कारण एवं निवारण, आर्गन व CO2 गैस, वेल्डिंग दोष और परीक्षण।',
    },
  },
  {
    id: 'res-es-01',
    tradeId: 'employability-skills',
    yearOrSem: 1,
    subject: 'Employability Skills',
    title: {
      en: 'Employability Skills 2024 Revised Curriculum (Bharat Skills Standard)',
      hi: 'एम्प्लॉयबिलिटी स्किल्स 2024 संशोधित पाठ्यक्रम (भारत स्किल्स मानक)',
    },
    authorOrSource: 'DGT / Quest Alliance / Bharat Skills',
    type: 'pdf',
    fileSize: '15.5 MB',
    downloadUrl: '#download-es-pdf',
    isNimiStandard: true,
    tags: ['English Literacy', 'Interview Skills', 'Digital Literacy', 'Entrepreneurship'],
    readTime: '120 Hours Content',
    summary: {
      en: 'Revised CTS syllabus: Professional email writing, job interviews, basic financial literacy (UPI, Banking, Mudra Yojana), workplace etiquette, POSH laws, and green transition.',
      hi: 'ईमेल लेखन, इंटरव्यू की तैयारी, डिजिटल वित्तीय साक्षरता (यूपीआई, मुद्रा योजना), कार्यस्थल शिष्टाचार और हरित कौशल।',
    },
  },
  {
    id: 'res-wcs-01',
    tradeId: 'workshop-calc-science',
    yearOrSem: 1,
    subject: 'Workshop Calculation & Science',
    title: {
      en: 'Workshop Calculation & Science (1st & 2nd Year Complete Guide)',
      hi: 'कार्यशाला गणना एवं विज्ञान (प्रथम एवं द्वितीय वर्ष संपूर्ण गाइड)',
    },
    authorOrSource: 'NIMI / SCVT UP',
    type: 'pdf',
    fileSize: '17.3 MB',
    downloadUrl: '#download-wcs-pdf',
    isNimiStandard: true,
    tags: ['Units & Fractions', 'Square Roots', 'Density', 'Lever & Pulleys', 'Heat & Work'],
    readTime: '40 Modules',
    summary: {
      en: 'Essential calculations for technical trades: SI & MKS units, mass, weight & density, speed and acceleration, mechanical advantage of levers, and Ohm’s law power calculations.',
      hi: 'एसआई व एमकेएस इकाइयां, द्रव्यमान, घनत्व, चाल एवं वेग, उत्तोलक का यांत्रिक लाभ और विद्युत शक्ति गणनाएं।',
    },
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'q-elec-01',
    tradeId: 'electrician',
    module: 'Basic Electricity & Safety',
    questionNumber: 1,
    text: {
      en: 'What is the unit of electric current according to the SI system?',
      hi: 'एसआई (SI) प्रणाली के अनुसार विद्युत धारा (Electric Current) की इकाई क्या है?',
    },
    options: [
      { id: 'A', text: { en: 'Volt', hi: 'वोल्ट' } },
      { id: 'B', text: { en: 'Ampere', hi: 'एम्पीयर' } },
      { id: 'C', text: { en: 'Ohm', hi: 'ओम' } },
      { id: 'D', text: { en: 'Watt', hi: 'वाट' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'The SI unit of electric current is Ampere (A), named after André-Marie Ampère. 1 Ampere equals 1 Coulomb of charge flowing per second.',
      hi: 'विद्युत धारा की एसआई इकाई एम्पीयर (A) है। 1 एम्पीयर का अर्थ प्रति सेकंड 1 कूलॉम आवेश का प्रवाहित होना है।',
    },
    difficulty: 'Easy',
  },
  {
    id: 'q-elec-02',
    tradeId: 'electrician',
    module: 'Magnetism & DC Machines',
    questionNumber: 2,
    text: {
      en: 'Which rule is used to determine the direction of induced EMF in a DC Generator armature conductor?',
      hi: 'डीसी जनरेटर के आर्मेचर चालक में प्रेरित विद्युत वाहक बल (EMF) की दिशा निर्धारित करने के लिए किस नियम का उपयोग किया जाता है?',
    },
    options: [
      { id: 'A', text: { en: 'Fleming’s Left Hand Rule', hi: 'फ्लेमिंग का बायां हाथ नियम' } },
      { id: 'B', text: { en: 'Fleming’s Right Hand Rule', hi: 'फ्लेमिंग का दायां हाथ नियम' } },
      { id: 'C', text: { en: 'Right Hand Thumb Rule', hi: 'दाएं हाथ का अंगूठा नियम' } },
      { id: 'D', text: { en: 'Corkscrew Rule', hi: 'कॉर्कस्क्रू नियम' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'Fleming\'s Right Hand Rule is used for Generators (induced EMF), where the thumb points to the motion, forefinger to the magnetic field, and middle finger to induced current.',
      hi: 'जनरेटर में प्रेरित ईएमएफ की दिशा ज्ञात करने हेतु फ्लेमिंग के दाएं हाथ का नियम प्रयुक्त होता है, जबकि मोटर के लिए बाएं हाथ का नियम उपयोग होता है।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'q-elec-03',
    tradeId: 'electrician',
    module: 'AC Circuits & Transformer',
    questionNumber: 3,
    text: {
      en: 'What type of loss is minimized by laminating the core of a transformer?',
      hi: 'ट्रांसफार्मर के कोर को लैमिनेट (पटलित) करके किस प्रकार की हानि (Loss) को न्यूनतम किया जाता है?',
    },
    options: [
      { id: 'A', text: { en: 'Copper Loss', hi: 'ताम्र हानि (कॉपर लॉस)' } },
      { id: 'B', text: { en: 'Hysteresis Loss', hi: 'शैथिल्य हानि (हिस्टैरिसीस लॉस)' } },
      { id: 'C', text: { en: 'Eddy Current Loss', hi: 'भंवर धारा हानि (एड्डी करंट लॉस)' } },
      { id: 'D', text: { en: 'Friction Loss', hi: 'घर्षण हानि' } },
    ],
    correctOption: 'C',
    explanation: {
      en: 'Laminating the iron core with insulation varnish breaks the circular path of induced eddy currents, significantly reducing Eddy Current Loss (P_e ∝ t²).',
      hi: 'कोर को पतली-पतली वार्निश युक्त पत्तियों (Laminations) में बांटने से भंवर धाराओं का प्रतिरोध बढ़ जाता है और भंवर धारा हानि (Eddy Current Loss) कम हो जाती है।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'q-elec-04',
    tradeId: 'electrician',
    module: 'Earthing & Safety',
    questionNumber: 4,
    text: {
      en: 'As per Indian Electricity Rules (IE Rules), what should be the maximum earth resistance for an ordinary electrical installation?',
      hi: 'भारतीय विद्युत नियमों (IE Rules) के अनुसार, एक सामान्य विद्युत संस्थापन (Installation) का अधिकतम अर्थ प्रतिरोध कितना होना चाहिए?',
    },
    options: [
      { id: 'A', text: { en: 'Not exceeding 1 Ohm', hi: '1 ओम से अधिक नहीं' } },
      { id: 'B', text: { en: 'Not exceeding 5 Ohms', hi: '5 ओम से अधिक नहीं' } },
      { id: 'C', text: { en: 'Not exceeding 20 Ohms', hi: '20 ओम से अधिक नहीं' } },
      { id: 'D', text: { en: 'Not exceeding 100 Ohms', hi: '100 ओम से अधिक नहीं' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'For domestic and small commercial installations, the earth resistance must not exceed 5 Ohms (large substations require < 1 Ohm or < 0.5 Ohm).',
      hi: 'घरेलू व सामान्य प्रतिष्ठानों के लिए अर्थिंग प्रतिरोध 5 ओम से कम होना चाहिए। बड़े पावर स्टेशनों में यह 0.5 से 1 ओम के भीतर रखा जाता है।',
    },
    difficulty: 'Hard',
  },
  {
    id: 'q-fit-01',
    tradeId: 'fitter',
    module: 'Precision Measuring Tools',
    questionNumber: 5,
    text: {
      en: 'What is the least count of a standard metric Vernier Caliper?',
      hi: 'एक मानक मीट्रिक वर्नियर कैलिपर का अल्पतमांक (Least Count) क्या होता है?',
    },
    options: [
      { id: 'A', text: { en: '0.1 mm', hi: '0.1 मिमी' } },
      { id: 'B', text: { en: '0.02 mm', hi: '0.02 मिमी' } },
      { id: 'C', text: { en: '0.01 mm', hi: '0.01 मिमी' } },
      { id: 'D', text: { en: '0.001 mm', hi: '0.001 मिमी' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'Least Count = 1 Main Scale Division (1 mm) - 1 Vernier Scale Division (49/50 mm) = 0.02 mm.',
      hi: 'मीट्रिक वर्नियर कैलिपर में 50 वर्नियर भाग 49 मुख्य पैमाने के भागों के बराबर होते हैं, जिससे अल्पतमांक = 1 - (49/50) = 0.02 मिमी प्राप्त होता है।',
    },
    difficulty: 'Easy',
  },
  {
    id: 'q-fit-02',
    tradeId: 'fitter',
    module: 'Bench Work & Files',
    questionNumber: 6,
    text: {
      en: 'Which grade of file is used to remove a heavy amount of metal quickly from a workpiece?',
      hi: 'कार्यखण्ड (Workpiece) से तेजी से अधिक मात्रा में धातु हटाने के लिए किस ग्रेड की रेती (File) का उपयोग किया जाता है?',
    },
    options: [
      { id: 'A', text: { en: 'Dead Smooth File', hi: 'डेड स्मूथ रेती' } },
      { id: 'B', text: { en: 'Smooth File', hi: 'स्मूथ रेती' } },
      { id: 'C', text: { en: 'Bastard File', hi: 'बास्टर्ड रेती' } },
      { id: 'D', text: { en: 'Second Cut File', hi: 'सेकंड कट रेती' } },
    ],
    correctOption: 'C',
    explanation: {
      en: 'Bastard files have coarse, widely spaced teeth and are designated for rapid, heavy material removal prior to fine finishing.',
      hi: 'बास्टर्ड फाइल के दांत मोटे और दूर-दूर होते हैं, इसलिए इसका उपयोग कार्यखण्ड से धातु को तेजी से छीलने (रफ फाइलिंग) के लिए किया जाता है।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'q-copa-01',
    tradeId: 'copa',
    module: 'Computer Architecture & Networks',
    questionNumber: 7,
    text: {
      en: 'Which of the following is considered non-volatile memory in a computer system?',
      hi: 'कंप्यूटर सिस्टम में निम्नलिखित में से किसे गैर-वाष्पशील मेमोरी (Non-Volatile Memory) माना जाता है?',
    },
    options: [
      { id: 'A', text: { en: 'RAM (Random Access Memory)', hi: 'रैम (RAM)' } },
      { id: 'B', text: { en: 'ROM (Read Only Memory)', hi: 'रोम (ROM)' } },
      { id: 'C', text: { en: 'SRAM Cache', hi: 'एसरैम कैश' } },
      { id: 'D', text: { en: 'Registers', hi: 'रजिस्टर' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'ROM retains stored BIOS instructions even after power is turned off, classifying it as non-volatile memory unlike RAM.',
      hi: 'रोम (ROM) में पावर सप्लाई बंद होने पर भी डेटा सुरक्षित रहता है, इसलिए यह नॉन-वोलेटाइल (स्थायी) मेमोरी है।',
    },
    difficulty: 'Easy',
  },
  {
    id: 'q-copa-02',
    tradeId: 'copa',
    module: 'Database & SQL',
    questionNumber: 8,
    text: {
      en: 'Which SQL command is classified under Data Definition Language (DDL)?',
      hi: 'डेटा डेफिनिशन लैंग्वेज (DDL) के अंतर्गत कौन सा SQL कमांड आता है?',
    },
    options: [
      { id: 'A', text: { en: 'SELECT', hi: 'SELECT' } },
      { id: 'B', text: { en: 'INSERT', hi: 'INSERT' } },
      { id: 'C', text: { en: 'CREATE', hi: 'CREATE' } },
      { id: 'D', text: { en: 'UPDATE', hi: 'UPDATE' } },
    ],
    correctOption: 'C',
    explanation: {
      en: 'DDL commands define and modify database schema structures (CREATE, ALTER, DROP, TRUNCATE). INSERT and UPDATE belong to DML.',
      hi: 'CREATE, ALTER, DROP और TRUNCATE कमांड DDL (डेटा परिभाषा) का हिस्सा हैं जो टेबल संरचना को निर्धारित करते हैं।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'q-es-01',
    tradeId: 'employability-skills',
    module: 'Communication & Digital Literacy',
    questionNumber: 9,
    text: {
      en: 'In professional email communication, what does "BCC" stand for?',
      hi: 'व्यावसायिक ईमेल संचार में "BCC" का पूर्ण रूप क्या होता है?',
    },
    options: [
      { id: 'A', text: { en: 'Best Courtesy Copy', hi: 'बेस्ट कर्टसी कॉपी' } },
      { id: 'B', text: { en: 'Blind Carbon Copy', hi: 'ब्लाइंड कार्बन कॉपी' } },
      { id: 'C', text: { en: 'Back Carbon Check', hi: 'बैक कार्बन चेक' } },
      { id: 'D', text: { en: 'Binary Code Communication', hi: 'बाइनरी कोड कम्युनिकेशन' } },
    ],
    correctOption: 'B',
    explanation: {
      en: 'BCC stands for Blind Carbon Copy. Recipients specified in BCC receive the email without their addresses being visible to other recipients.',
      hi: 'BCC का पूर्ण रूप ब्लाइंड कार्बन कॉपी (Blind Carbon Copy) है। इसमें जोड़े गए प्राप्तकर्ताओं के ईमेल पते अन्य प्राप्तकर्ताओं को दिखाई नहीं देते।',
    },
    difficulty: 'Easy',
  },
  {
    id: 'q-wcs-01',
    tradeId: 'workshop-calc-science',
    module: 'Units, Mass & Density',
    questionNumber: 10,
    text: {
      en: 'What is the density of pure water at 4 degrees Celsius in SI units?',
      hi: '4 डिग्री सेल्सियस पर शुद्ध जल का घनत्व एसआई इकाई में कितना होता है?',
    },
    options: [
      { id: 'A', text: { en: '1 kg/m³', hi: '1 किग्रा/मी³' } },
      { id: 'B', text: { en: '100 kg/m³', hi: '100 किग्रा/मी³' } },
      { id: 'C', text: { en: '1000 kg/m³', hi: '1000 किग्रा/मी³' } },
      { id: 'D', text: { en: '10,000 kg/m³', hi: '10,000 किग्रा/मी³' } },
    ],
    correctOption: 'C',
    explanation: {
      en: 'Pure water reaches maximum density at 4°C, which is 1 g/cm³ in CGS or 1000 kg/m³ in SI units.',
      hi: '4°C पर जल का घनत्व अधिकतम होता है, जो 1 ग्राम/सेमी³ या 1000 किलोग्राम प्रति घन मीटर (kg/m³) होता है।',
    },
    difficulty: 'Medium',
  },
];

export const USER_ROLES_INFO: RoleInfo[] = [
  {
    id: 'directorate',
    title: {
      en: 'Directorate (DTE UP)',
      hi: 'प्रशिक्षण एवं सेवायोजन निदेशालय',
    },
    badge: {
      en: 'Apex State Authority',
      hi: 'शीर्ष राज्य प्राधिकरण',
    },
    description: {
      en: 'State-level executive monitoring, district CBT analytics, policy circulars, and statewide assessment schedules.',
      hi: 'राज्य स्तरीय कार्यकारी समीक्षा, जिलावार सीबीटी एनालिटिक्स, नीतिगत परिपत्र एवं राज्यव्यापी परीक्षा अनुसूची।',
    },
    icon: 'Landmark',
  },
  {
    id: 'central_content',
    title: {
      en: 'Centralized Content & Assessment Cell',
      hi: 'केंद्रीकृत सामग्री एवं मूल्यांकन प्रकोष्ठ',
    },
    badge: {
      en: 'Academic & Exam Board',
      hi: 'पाठ्यक्रम एवं परीक्षा बोर्ड',
    },
    description: {
      en: 'Curates NIMI digital library, creates and audits bilingual question banks, configures blueprints, and handles Moodle/Hostinger exports.',
      hi: 'निमी डिजिटल लाइब्रेरी का संपादन, द्विभाषी प्रश्न बैंक निर्माण व ऑडिट, परीक्षा ब्लूप्रिंट व मूडल/होस्टिंगर एक्सपोर्ट।',
    },
    icon: 'Layers',
  },
  {
    id: 'iti_admin',
    title: {
      en: 'ITIs (Institutes & Principals)',
      hi: 'आईटीआई संस्थान व प्रधानाचार्य',
    },
    badge: {
      en: 'Institutional Center',
      hi: 'संस्थान प्रबंधन',
    },
    description: {
      en: 'Batch rosters, CBT computer lab slot scheduling, instructor assignments, attendance, and local trainee performance metrics.',
      hi: 'ट्रेनी बैच रोस्टर, सीबीटी कंप्यूटर लैब स्लॉट आवंटन, अनुदेशक कार्यभार, उपस्थिति एवं संस्थान स्तर पर प्रदर्शन समीक्षा।',
    },
    icon: 'School',
  },
  {
    id: 'trainee',
    title: {
      en: 'Trainees (Students)',
      hi: 'प्रशिक्षार्थी (छात्र/छात्रा)',
    },
    badge: {
      en: 'Learner & Candidate',
      hi: 'अध्ययन एवं परीक्षा परीक्षार्थी',
    },
    description: {
      en: 'Personalized study desk, access to NIMI textbooks & videos, real-time CBT mock tests, scorecards, and mistake revision book.',
      hi: 'व्यक्तिगत अध्ययन डेस्क, निमी ई-बुक्स व वीडियो, लाइव सीबीटी मॉक टेस्ट, स्कोरकार्ड व गलती सुधार नोटबुक।',
    },
    icon: 'GraduationCap',
  },
];

export const DIRECTORATE_DISTRICTS_DATA: DirectorateDistrictSummary[] = [
  {
    district: 'Lucknow',
    division: 'Lucknow Division',
    totalITIs: 18,
    enrolledStudents: 14850,
    testsCompleted: 12420,
    passPercentage: 88.4,
    topTrade: 'Electrician',
    averageAttendancePct: 91.2,
    status: 'excellent',
  },
  {
    district: 'Kanpur Nagar',
    division: 'Kanpur Division',
    totalITIs: 22,
    enrolledStudents: 17200,
    testsCompleted: 14100,
    passPercentage: 86.8,
    topTrade: 'Fitter',
    averageAttendancePct: 89.5,
    status: 'excellent',
  },
  {
    district: 'Varanasi',
    division: 'Varanasi Division',
    totalITIs: 14,
    enrolledStudents: 11400,
    testsCompleted: 9850,
    passPercentage: 85.2,
    topTrade: 'Electrician',
    averageAttendancePct: 88.0,
    status: 'normal',
  },
  {
    district: 'Prayagraj',
    division: 'Prayagraj Division',
    totalITIs: 16,
    enrolledStudents: 13100,
    testsCompleted: 10920,
    passPercentage: 84.6,
    topTrade: 'COPA',
    averageAttendancePct: 87.4,
    status: 'normal',
  },
  {
    district: 'Meerut',
    division: 'Meerut Division',
    totalITIs: 15,
    enrolledStudents: 12600,
    testsCompleted: 11050,
    passPercentage: 89.1,
    topTrade: 'Fitter',
    averageAttendancePct: 92.1,
    status: 'excellent',
  },
  {
    district: 'Agra',
    division: 'Agra Division',
    totalITIs: 19,
    enrolledStudents: 15300,
    testsCompleted: 11980,
    passPercentage: 82.5,
    topTrade: 'Welder',
    averageAttendancePct: 84.7,
    status: 'normal',
  },
  {
    district: 'Gorakhpur',
    division: 'Gorakhpur Division',
    totalITIs: 17,
    enrolledStudents: 13900,
    testsCompleted: 10840,
    passPercentage: 83.9,
    topTrade: 'Electrician',
    averageAttendancePct: 86.3,
    status: 'normal',
  },
  {
    district: 'Bareilly',
    division: 'Bareilly Division',
    totalITIs: 12,
    enrolledStudents: 9800,
    testsCompleted: 7640,
    passPercentage: 79.4,
    topTrade: 'Electronic Mechanic',
    averageAttendancePct: 81.2,
    status: 'attention',
  },
  {
    district: 'Jhansi',
    division: 'Jhansi Division',
    totalITIs: 10,
    enrolledStudents: 8200,
    testsCompleted: 6950,
    passPercentage: 81.2,
    topTrade: 'Fitter',
    averageAttendancePct: 83.5,
    status: 'normal',
  },
  {
    district: 'Moradabad',
    division: 'Moradabad Division',
    totalITIs: 11,
    enrolledStudents: 8900,
    testsCompleted: 6810,
    passPercentage: 78.6,
    topTrade: 'Electrician',
    averageAttendancePct: 79.8,
    status: 'attention',
  },
  {
    district: 'Ayodhya',
    division: 'Ayodhya Division',
    totalITIs: 13,
    enrolledStudents: 10450,
    testsCompleted: 8720,
    passPercentage: 85.0,
    topTrade: 'COPA',
    averageAttendancePct: 88.6,
    status: 'normal',
  },
  {
    district: 'Aligarh',
    division: 'Aligarh Division',
    totalITIs: 12,
    enrolledStudents: 9400,
    testsCompleted: 7890,
    passPercentage: 82.8,
    topTrade: 'Mechanic Diesel',
    averageAttendancePct: 85.1,
    status: 'normal',
  },
];

export const STATE_CIRCULARS: StateCircular[] = [
  {
    id: 'circ-2026-01',
    number: 'DTE/EXAM/CBT/2026/1042',
    date: '14 Feb 2026',
    title: {
      en: 'Mandatory Conduction of NIMI Aligned Pre-AITT CBT Mock Assessments across all 75 Districts',
      hi: 'सभी 75 जनपदों के राजकीय एवं निजी आईटीआई में निमी आधारित प्री-एआईटीटी सीबीटी मॉक टेस्ट का अनिवार्य आयोजन',
    },
    category: 'Examination',
    downloadSize: '1.4 MB (PDF)',
    signedBy: 'Director of Training, UP Lucknow',
    isUrgent: true,
  },
  {
    id: 'circ-2026-02',
    number: 'SCVT/CURR/REV/2026/89',
    date: '02 Feb 2026',
    title: {
      en: 'Integration of Updated Employability Skills & Cyber Security Modules in Digital Library',
      hi: 'डिजिटल लाइब्रेरी में नवीनतम एम्प्लॉयबिलिटी स्किल्स एवं साइबर सुरक्षा मॉड्यूल का समावेश',
    },
    category: 'Curriculum',
    downloadSize: '890 KB (PDF)',
    signedBy: 'Joint Director (Curriculum & Standards), SCVT UP',
    isUrgent: false,
  },
  {
    id: 'circ-2026-03',
    number: 'DTE/INFRA/LAB/2026/512',
    date: '22 Jan 2026',
    title: {
      en: 'Computer Lab Infrastructure Audit & LAN Connectivity Readiness for Centralized CBT Engine',
      hi: 'केंद्रीकृत सीबीटी परीक्षा इंजन हेतु कंप्यूटर लैब अवसंरचना ऑडिट एवं लैन कनेक्टिविटी तत्परता प्रमाणन',
    },
    category: 'Administration',
    downloadSize: '2.1 MB (PDF)',
    signedBy: 'Nodal Officer (IT & Examination), DTE UP',
    isUrgent: true,
  },
];

export const SAMPLE_ASSESSMENT_BLUEPRINTS: AssessmentBlueprint[] = [
  {
    id: 'bp-electrician-annual',
    title: {
      en: 'AITT CTS All India Electrician CBT Annual Pattern',
      hi: 'एआईटीटी सीटीएस अखिल भारतीय इलेक्ट्रीशियन वार्षिक सीबीटी पैटर्न',
    },
    tradeId: 'electrician',
    examType: 'Annual AITT CBT',
    durationMinutes: 120,
    totalQuestions: 75,
    totalMarks: 150,
    passingPercentage: 40,
    negativeMarking: false,
    sections: [
      { name: 'Trade Theory', questionCount: 38, marksPerQuestion: 2 },
      { name: 'Workshop Calculation & Science', questionCount: 6, marksPerQuestion: 2 },
      { name: 'Engineering Drawing', questionCount: 6, marksPerQuestion: 2 },
      { name: 'Employability Skills', questionCount: 25, marksPerQuestion: 2 },
    ],
    active: true,
  },
  {
    id: 'bp-fitter-annual',
    title: {
      en: 'AITT CTS Fitter Comprehensive CBT Blueprint',
      hi: 'एआईटीटी सीटीएस फ़िटर समग्र सीबीटी ब्लूप्रिंट',
    },
    tradeId: 'fitter',
    examType: 'Annual AITT CBT',
    durationMinutes: 120,
    totalQuestions: 75,
    totalMarks: 150,
    passingPercentage: 40,
    negativeMarking: false,
    sections: [
      { name: 'Trade Theory', questionCount: 38, marksPerQuestion: 2 },
      { name: 'Workshop Calculation & Science', questionCount: 6, marksPerQuestion: 2 },
      { name: 'Engineering Drawing', questionCount: 6, marksPerQuestion: 2 },
      { name: 'Employability Skills', questionCount: 25, marksPerQuestion: 2 },
    ],
    active: true,
  },
  {
    id: 'bp-copa-annual',
    title: {
      en: 'COPA Theory & Employability Skills Combined CBT',
      hi: 'कोपा थ्योरी एवं एम्प्लॉयबिलिटी स्किल्स संयुक्त सीबीटी',
    },
    tradeId: 'copa',
    examType: 'Annual AITT CBT',
    durationMinutes: 90,
    totalQuestions: 50,
    totalMarks: 100,
    passingPercentage: 40,
    negativeMarking: false,
    sections: [
      { name: 'Trade Theory (Hardware, DBMS, Python, Web)', questionCount: 30, marksPerQuestion: 2 },
      { name: 'Employability Skills', questionCount: 20, marksPerQuestion: 2 },
    ],
    active: true,
  },
];

export const SAMPLE_ITI_BATCHES: ITIBatch[] = [
  {
    id: 'b-el-01',
    itiCode: 'ITI-0101',
    tradeId: 'electrician',
    batchYear: '2024-2026',
    semester: 2,
    section: 'A',
    totalTrainees: 42,
    cbtEligibleCount: 40,
    instructorName: 'Er. Rajesh Kumar Sharma',
    averageScorePct: 86.4,
  },
  {
    id: 'b-el-02',
    itiCode: 'ITI-0101',
    tradeId: 'electrician',
    batchYear: '2024-2026',
    semester: 2,
    section: 'B',
    totalTrainees: 40,
    cbtEligibleCount: 39,
    instructorName: 'Er. Alok Verma',
    averageScorePct: 82.1,
  },
  {
    id: 'b-fit-01',
    itiCode: 'ITI-0101',
    tradeId: 'fitter',
    batchYear: '2024-2026',
    semester: 2,
    section: 'A',
    totalTrainees: 38,
    cbtEligibleCount: 37,
    instructorName: 'Shri Manoj Yadav',
    averageScorePct: 84.7,
  },
  {
    id: 'b-copa-01',
    itiCode: 'ITI-0101',
    tradeId: 'copa',
    batchYear: '2025-2026',
    semester: 1,
    section: 'A',
    totalTrainees: 48,
    cbtEligibleCount: 46,
    instructorName: 'Smt. Priya Srivastava',
    averageScorePct: 89.2,
  },
  {
    id: 'b-weld-01',
    itiCode: 'ITI-0101',
    tradeId: 'welder',
    batchYear: '2025-2026',
    semester: 1,
    section: 'A',
    totalTrainees: 32,
    cbtEligibleCount: 30,
    instructorName: 'Shri Dinesh Chandra',
    averageScorePct: 81.0,
  },
];

export const SAMPLE_LAB_SESSIONS: ITILabSession[] = [
  {
    id: 'lab-ses-1',
    itiCode: 'ITI-0101',
    labName: 'Central Computer Lab 1 (Main Block)',
    totalPCs: 50,
    activeTrade: 'Electrician (Batch A & B)',
    shift: 'Morning (09:30 - 11:30)',
    scheduledDate: 'Tomorrow, 10:00 AM',
    status: 'Ready',
    invigilator: 'Shri S.K. Mishra & Smt. Priya S.',
  },
  {
    id: 'lab-ses-2',
    itiCode: 'ITI-0101',
    labName: 'COPA Digital Multimedia Lab',
    totalPCs: 45,
    activeTrade: 'COPA & Fitter',
    shift: 'Afternoon (12:30 - 02:30)',
    scheduledDate: 'Tomorrow, 01:00 PM',
    status: 'Ready',
    invigilator: 'Er. Alok Verma',
  },
  {
    id: 'lab-ses-3',
    itiCode: 'ITI-0101',
    labName: 'Workshop CAD/CBT Annex Lab',
    totalPCs: 35,
    activeTrade: 'Welder & Electronic Mechanic',
    shift: 'Evening (03:30 - 05:30)',
    scheduledDate: 'Upcoming Saturday',
    status: 'Ready',
    invigilator: 'Shri Manoj Yadav',
  },
];

export const SAMPLE_TRAINEE_ACCOUNTS: TraineeAccount[] = [
  {
    id: 'tr-01',
    rollNumber: 'UP240231010189',
    fullName: 'Amit Kumar Maurya',
    tradeId: 'electrician',
    itiCode: 'ITI-0101',
    semester: 2,
    registrationYear: '2024',
    fatherName: 'Ram Sevak Maurya',
    category: 'OBC',
    mobile: '+91 98391 *****',
    mockTestsTaken: 6,
    averageScore: 84.5,
    lastTestDate: 'Yesterday, 04:30 PM',
    status: 'Exam Registered',
  },
  {
    id: 'tr-02',
    rollNumber: 'UP240227010214',
    fullName: 'Mohammad Shahid Khan',
    tradeId: 'fitter',
    itiCode: 'ITI-0101',
    semester: 2,
    registrationYear: '2024',
    fatherName: 'Noor Mohammad',
    category: 'General',
    mobile: '+91 94150 *****',
    mockTestsTaken: 5,
    averageScore: 81.2,
    lastTestDate: '3 days ago',
    status: 'Exam Registered',
  },
  {
    id: 'tr-03',
    rollNumber: 'UP250242010045',
    fullName: 'Neha Kumari Gautam',
    tradeId: 'copa',
    itiCode: 'ITI-0101',
    semester: 1,
    registrationYear: '2025',
    fatherName: 'Harish Chandra Gautam',
    category: 'SC',
    mobile: '+91 87654 *****',
    mockTestsTaken: 8,
    averageScore: 91.0,
    lastTestDate: 'Today, 10:15 AM',
    status: 'Exam Registered',
  },
  {
    id: 'tr-04',
    rollNumber: 'UP250246010022',
    fullName: 'Vikram Singh Patel',
    tradeId: 'welder',
    itiCode: 'ITI-0101',
    semester: 1,
    registrationYear: '2025',
    fatherName: 'Bhanu Pratap Singh',
    category: 'OBC',
    mobile: '+91 79051 *****',
    mockTestsTaken: 4,
    averageScore: 78.4,
    lastTestDate: '4 days ago',
    status: 'Exam Registered',
  },
];

export const SAMPLE_MISTAKES_DATA: TraineeMistakeItem[] = [
  {
    questionId: 'q-elec-02',
    tradeId: 'electrician',
    topic: 'Electrical Machines & Transformers',
    questionText: {
      en: 'Which instrument is used to measure electrical insulation resistance directly?',
      hi: 'विद्युत रोधन प्रतिरोध (Insulation Resistance) को सीधे मापने के लिए किस उपकरण का उपयोग किया जाता है?',
    },
    selectedOption: 'B. Multimeter (मल्टीमीटर)',
    correctOption: 'C. Megger (मेगर)',
    explanation: {
      en: 'A Megger is a specialized high-resistance ohmmeter with a hand-driven generator, designed to measure insulation resistances in megaohms.',
      hi: 'इंसुलेशन प्रतिरोध मापने के लिए विशेष रूप से मेगर (Megger) का उपयोग किया जाता है, जो मेगा-ओम में उच्च प्रतिरोध मापता है।',
    },
  },
  {
    questionId: 'q-elec-05',
    tradeId: 'electrician',
    topic: 'DC Generators',
    questionText: {
      en: 'What is the purpose of carbon brushes in a DC generator?',
      hi: 'डीसी जनरेटर में कार्बन ब्रश का मुख्य उद्देश्य क्या होता है?',
    },
    selectedOption: 'D. To increase armature flux',
    correctOption: 'B. Collect current from commutator segments',
    explanation: {
      en: 'Carbon brushes maintain sliding electrical contact with the commutator segments to collect generated current without causing severe sparking.',
      hi: 'कार्बन ब्रश कम्यूटेटर सेगमेंट से करंट एकत्र करके बाहरी परिपथ तक सुगमता से पहुंचाते हैं।',
    },
  },
];

export const STATE_SCHEDULED_EXAMS: import('./types').ScheduledStateExam[] = [
  {
    id: 'exam-up-01',
    title: {
      en: 'Pre-AITT State Mock CBT Phase 1 (Electrician & Fitter)',
      hi: 'प्री-एआईटीटी राज्य स्तरीय मॉक टेस्ट चरण 1 (इलेक्ट्रीशियन व फ़िटर)',
    },
    tradeId: 'electrician',
    examType: 'Statewide Pre-AITT Mock',
    dateRange: 'Feb 24 - Mar 10, 2026',
    durationMinutes: 120,
    totalQuestions: 75,
    totalMarks: 150,
    targetITIs: 'All 315 Government ITIs',
    passcode: 'SCVT-UP-LOCK-2026A',
    status: 'Live',
    registeredCount: 38400,
    activationStartTime: '2026-02-24T09:00:00',
    activationEndTime: '2026-03-10T18:00:00',
    shiftTimeSlot: 'Shift 1: 09:30 AM - 11:30 AM & Shift 2: 02:00 PM - 04:00 PM',
    isActivatedNow: true,
    requiresOtpAuth: true,
    demoOtpCode: '749210',
    invigilatorName: 'Er. R. K. Srivastava (Exam Supdt)',
    otpCooldownSeconds: 60,
  },
  {
    id: 'exam-up-02',
    title: {
      en: 'COPA & 1-Year CTS Trades State CBT Assessment',
      hi: 'कोपा एवं 1-वर्षीय ट्रेड सीबीटी राज्य स्तरीय मूल्यांकन',
    },
    tradeId: 'copa',
    examType: 'Quarterly SCVT Assessment',
    dateRange: 'Mar 12 - Mar 15, 2026',
    durationMinutes: 90,
    totalQuestions: 50,
    totalMarks: 100,
    targetITIs: 'All 75 Districts (Govt + Pvt ITIs)',
    passcode: 'COPA-SCVT-PASS-884',
    status: 'Scheduled',
    registeredCount: 16200,
    activationStartTime: '2026-03-12T10:00:00',
    activationEndTime: '2026-03-15T16:00:00',
    shiftTimeSlot: 'Shift 1: 10:00 AM - 11:30 AM',
    isActivatedNow: false,
    requiresOtpAuth: true,
    demoOtpCode: '483921',
    invigilatorName: 'Dr. Neha Verma (Chief Invigilator)',
    otpCooldownSeconds: 60,
  },
  {
    id: 'exam-up-03',
    title: {
      en: 'Workshop Calculation & Science Mid-Term Diagnostic CBT',
      hi: 'कार्यशाला गणना एवं विज्ञान मध्यावधि निदानात्मक सीबीटी',
    },
    tradeId: 'workshop-calc-science',
    examType: 'Diagnostic Unit Test',
    dateRange: 'Mar 22 - Mar 24, 2026',
    durationMinutes: 60,
    totalQuestions: 25,
    totalMarks: 50,
    targetITIs: 'All Affiliated ITIs',
    passcode: 'WCS-UP-DIAG-441',
    status: 'Scheduled',
    registeredCount: 42000,
    activationStartTime: '2026-03-22T09:30:00',
    activationEndTime: '2026-03-24T17:00:00',
    shiftTimeSlot: 'Shift 1: 09:30 AM - 10:30 AM',
    isActivatedNow: false,
    requiresOtpAuth: true,
    demoOtpCode: '592014',
    invigilatorName: 'Er. Alok Sharma (Nodal Officer)',
    otpCooldownSeconds: 60,
  },
];

export const DEFAULT_PORTAL_USERS: import('./types').AuthenticatedUser[] = [
  {
    id: 'usr-dir-01',
    username: 'director.scvt',
    name: 'Dr. Hari Om, IAS',
    role: 'directorate',
    designation: {
      en: 'Principal Secretary & State Directorate General',
      hi: 'प्रमुख सचिव एवं राज्य महानिदेशक, व्यावसायिक शिक्षा',
    },
    departmentOrITI: 'DTE & SCVT Headquarters, Lucknow',
    avatarInitials: 'HO',
    email: 'director.training@up.gov.in',
    mobile: '+91 94150 11001',
    employeeOrRollId: 'UP-DTE-DIR-001',
    lastLogin: 'Today, 09:15 AM',
    token: 'jwt-sec-dir-dte-9901',
    twoFactorEnabled: true,
  },
  {
    id: 'usr-content-01',
    username: 'assessment.cell',
    name: 'Er. Shailendra Verma',
    role: 'central_content',
    designation: {
      en: 'Joint Director (Curriculum, NIMI & Assessment Cell)',
      hi: 'संयुक्त निदेशक (पाठ्यक्रम, निमी एवं परीक्षा प्रकोष्ठ)',
    },
    departmentOrITI: 'State Central Assessment & Question Cell, Lucknow',
    avatarInitials: 'SV',
    email: 'assessment.scvt@up.gov.in',
    mobile: '+91 98390 22002',
    employeeOrRollId: 'UP-SCVT-CC-104',
    lastLogin: 'Today, 08:45 AM',
    token: 'jwt-sec-cont-scvt-5521',
    twoFactorEnabled: true,
  },
  {
    id: 'usr-iti-01',
    username: 'supdt.aliganj',
    name: 'Er. Rajesh Kumar Srivastava',
    role: 'iti_admin',
    designation: {
      en: 'Center Superintendent & Vice Principal',
      hi: 'केंद्र अधीक्षक एवं उप प्रधानाचार्य',
    },
    departmentOrITI: 'Govt. ITI Aliganj, Lucknow (Code: ITI-0101)',
    avatarInitials: 'RS',
    email: 'principal.itialiganj@up.gov.in',
    mobile: '+91 94152 33003',
    employeeOrRollId: 'ITI-0101-SUPDT',
    lastLogin: 'Today, 10:02 AM',
    token: 'jwt-sec-iti-0101-4433',
    twoFactorEnabled: true,
  },
  {
    id: 'usr-trainee-01',
    username: 'UP240223010198',
    name: 'Ankit Kumar Maurya',
    role: 'trainee',
    designation: {
      en: 'Trainee Apprentice - Electrician (CTS Year II)',
      hi: 'प्रशिक्षार्थी - इलेक्ट्रीशियन (द्विवार्षिक सीटीएस)',
    },
    departmentOrITI: 'Govt. ITI Aliganj, Lucknow (Code: ITI-0101)',
    avatarInitials: 'AM',
    email: 'ankit.maurya@iti.up.gov.in',
    mobile: '+91 98391 44004',
    employeeOrRollId: 'UP240223010198',
    lastLogin: 'Yesterday, 04:30 PM',
    token: 'jwt-sec-tr-240223-8812',
    twoFactorEnabled: true,
  },
];
